name: Test all platforms

on: [ pull_request, merge_group ]

env:
  COVERALLS_SERVICE_NUMBER: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}

jobs:
  test-linux:
    uses: ./.github/workflows/test.yml
    secrets:
      token: ${{ secrets.COVERALLS_REPO_TOKEN }}

  coveralls:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [test-linux]
    steps:
    - uses: coverallsapp/github-action@v2
      with:
        carryforward: "linux-1,linux-2"
        parallel-finished: true
